sonar.projectKey=api
sonar.projectName=api
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,__tests__/**
sonar.tests=__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://10.0.2.15:9000
sonar.token=sqp_f1aa11b84ca1938892f093163e108a365511b164
